### ISSUE TITLE
Raivo, mime types, and file uploads

### ISSUE THREAD

**Issue by Anniepoo** [Anniepoo/swiplwebtut#12]
Raivo went through some hell with multipart file uploads.  The section on file upload should at least refer to all this.

I'll see if I can assign this to Raivo. - nope, he's not in project.

**Comment by rla** [comment]
Lots of it was discussed in the mailing list:
https://groups.google.com/forum/#!searchin/swi-prolog/file$20upload/swi-prolog/ABzhD4EKKAY/xj_nxVsKqxUJ

Anyway, I was using AJAX file uploads which cuts off mime (no multipart) altogether:
https://github.com/rla/blog-core/blob/master/prolog/bc/bc_api_file.pl#L101

This was much easier than dealing with things assuming/guessing mime part encodings, or worse, tying them to the system default encoding, for no reason at all.

If you test it, make sure you test with binary files (images), text files containing ascii only and text files containing utf-8 non-ascii-subset characters.

**Comment by Anniepoo** [comment]
closing as documented by 'see mail list discussion'
